version: "3"

services:
  db-postgres-apisolidfindfriend:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    container_name: "db-postgres-apisolidfindfriend"
    restart: always
    volumes:
      - ./banco-de-dados-apisolidfindfriend:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpg

volumes:
 banco-de-dados-apisolidfindfriend: